"""The built-in rails: things that must never be suspended.

Kept in the engine package because it is engine data, not application
configuration: every frontend (and every future one) has to inherit exactly this
list.  Users may add to it; nothing may take away from it, because losing a rail
is what turns "I was distracted" into "my desktop froze".
"""

#: Things that must never be killed, because doing so breaks the game, the
#: desktop session, or the user's ability to recover.  Users may add to this
#: list; the fail-closed evaluation order means additions are always safe.
DEFAULT_PROTECT_NAMES = frozenset({
    "Chill With You", "Chill With You.", "Hyprland", "NetworkManager",
    "X", "Xorg", "Xwayland", "accounts-daemon",
    "agreety", "ags", "alacritty", "albert",
    "anyrun", "as", "ash", "at-spi-bus-laun",
    "at-spi2-registr", "avahi-daemon", "awesome", "awk",
    "base64", "basename", "bash", "bc",
    "bemenu", "bluetoothd", "bspwm", "btop",
    "bubblewrap", "bun", "busybox", "bwrap",
    "bzip2", "cage", "cargo", "cat",
    "cc", "chillfocus-laun", "chillfocusd", "chmod",
    # The backend itself, and its launcher: focusedd holds the frozen state, so
    # freezing it would be the one mistake nothing could recover from.  The
    # engine also refuses to touch its own pid, but a name rail costs nothing.
    "focusedd", "focused-launch", "focusedd.py",
    "chown", "chrome_crashpad", "cinnamon", "cinnamon-sessio",
    "cinnamon-settin", "clang", "cliphist", "clipman",
    "cmake", "column", "comm", "conhost.exe",
    "cosmic-comp", "cosmic-session", "cp", "crashpad_handle",
    "csh", "csplit", "cupsd", "curl",
    "cut", "dash", "date", "dbus-broker",
    "dbus-broker-lau", "dbus-daemon", "dd", "deepseek-harnes",
    "deno", "df", "diff", "dig",
    "dirname", "dmenu", "dmenu_run", "dmesg",
    "dotnet", "du", "dunst", "dwm",
    "echo", "egrep", "electron", "elogind",
    "env", "eww", "explorer.exe", "expr",
    "false", "fcitx", "fcitx5", "fd",
    "fgrep", "file", "find", "fish",
    "flatpak", "flatpak-portal", "flatpak-session", "flock",
    "fluxbox", "fmt", "fnott", "fold",
    "foot", "footclient", "free", "fusermount",
    "fusermount3", "fuzzel", "g++", "gamemoderun",
    "gamescope", "gawk", "gcc", "gdb",
    "gdm", "gdm3", "ghostty", "git",
    "gnome-keyring-d", "gnome-panel", "gnome-session-b", "gnome-shell",
    "gnome-terminal", "gnome-terminal-", "go", "gpg-agent",
    "gradle", "greenclip", "greetd", "grep",
    "groups", "gsd-a11y-settin", "gsd-clipboard", "gsd-color",
    "gsd-datetime", "gsd-disk-utilit", "gsd-housekeepin", "gsd-keyboard",
    "gsd-media-keys", "gsd-mouse", "gsd-power", "gsd-rfkill",
    "gsd-screensaver", "gsd-sharing", "gsd-sound", "gsd-wacom",
    "gsd-xsettings", "guake", "gunzip", "gvfs-udisks2-vo",
    "gvfsd", "gvfsd-dnssd", "gvfsd-fuse", "gvfsd-metadata",
    "gvfsd-network", "gvfsd-trash", "gzip", "head",
    "herbstluftwm", "hexdump", "hg", "host",
    "hostname", "htop", "i3", "i3bar",
    "ibus-daemon", "ibus-x11", "icewm", "id",
    "ifconfig", "ionice", "ip", "java",
    "javac", "javaw", "join", "journalctl",
    "jq", "jwm", "kanshi", "kded5",
    "kded6", "kglobalaccel5", "kglobalaccel6", "kill",
    "killall", "kitten", "kitty", "konsole",
    "kscreenlocker_g", "ksecretd", "ksh", "ksmserver",
    "kwalletd5", "kwalletd6", "kwin", "kwin_wayland",
    "kwin_x11", "labwc", "ld", "less",
    "lightdm", "lightdm-gtk-gre", "ln", "locate",
    "ls", "lsof", "ltrace", "lxdm",
    "lxpolkit", "lxqt-panel", "lxqt-session", "lxterminal",
    "ly", "make", "mako", "man",
    "mangohud", "marco", "mate-panel", "mate-polkit",
    "mate-session", "mate-settings-d", "mate-terminal", "mawk",
    "md5sum", "metacity", "mkdir", "mktemp",
    "mono", "mono-sgen", "more", "mount",
    "mutter", "mv", "mvn", "nc",
    "netstat", "nice", "ninja", "niri",
    "nl", "node", "nodejs", "nohup",
    "npm", "nslookup", "nu", "od",
    "openbox", "parallel", "paste", "patch",
    "perl", "pgrep", "pidof", "ping",
    "pip", "pip3", "pipewire", "pipewire-media-",
    "pipewire-pulse", "pkg-config", "pkill", "plasma-desktop",
    "plasma_session", "plasmashell", "plugplay.exe", "pnpm",
    "polkit-*", "polkit-gnome-au", "polkit-kde-auth", "polkitd",
    "polybar", "pr", "pressure-vessel", "printenv",
    "printf", "proton", "ps", "pulseaudio",
    "pv-adverb", "pv-bwrap", "python", "python3",
    "python3.10", "python3.11", "python3.12", "python3.13",
    "python3.14", "qs", "qtile", "quickshell",
    "readlink", "realpath", "reaper", "renice",
    "rg", "ripgrep", "river", "rm",
    "rmdir", "rofi", "rsync", "rtkit-daemon",
    "ruby", "rustc", "screen", "sddm",
    "sddm-helper", "seatd", "sed", "seq",
    "services.exe", "setsid", "sh", "sha256sum",
    "shred", "sleep", "slim", "socat",
    "sort", "split", "srt-bwrap", "srt-logger",
    "ss", "ssh-agent", "sshd", "st",
    "start.exe", "startx", "stat", "stdbuf",
    "steam", "steam-runtime-l", "steamlaunch", "steamwebhelper",
    "strace", "strings", "svn", "sway",
    "swaybar", "swayidle", "swaync", "swayosd",
    "swayosd-server", "sync", "systemctl", "systemd",
    "systemd-*", "systemd-homed", "systemd-journal", "systemd-logind",
    "systemd-oomd", "systemd-resolve", "systemd-timesyn", "systemd-udevd",
    "systemd-userdbd", "tac", "tail", "tar",
    "taskset", "tcsh", "tee", "terminator",
    "test", "tilix", "timeout", "tmux",
    "top", "touch", "tr", "traceroute",
    "tree", "true", "truncate", "type",
    "udisksd", "ulauncher", "umount", "uname",
    "uniq", "unzip", "updatedb", "upowerd",
    "uptime", "urxvt", "vkbasalt", "vmstat",
    "watch", "waybar", "wayfire", "wc",
    "wezterm", "wezterm-gui", "wget", "whereis",
    "which", "whoami", "wine", "wine-preloader",
    "wine64", "wine64-preloade", "winedevice.exe", "wineserver",
    "wireplumber", "wl-clipboard", "wl-copy", "wl-paste",
    "wlr-randr", "wob", "wofi", "wpa_supplicant",
    "xargs", "xdg-dbus-proxy", "xdg-desktop-por", "xdg-document-po",
    "xdg-permission-", "xdm", "xfce4-panel", "xfce4-session",
    "xfce4-terminal", "xfdesktop", "xfsettingsd", "xfwm4",
    "xinit", "xmonad", "xsettingsd", "xterm",
    "xwayland-satell", "xxd", "xz", "yakuake",
    "yambar", "yarn", "yes", "yq",
    "zip", "zsh", "zstd",
})
